//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulosdetalleinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulosdetalleinv()
        {
            this.cotizacionesinvdetalle = new HashSet<cotizacionesinvdetalle>();
            this.movimientosdetalleinv = new HashSet<movimientosdetalleinv>();
            this.pedidosclientesinvdetalle = new HashSet<pedidosclientesinvdetalle>();
        }
    
        public int IdInternoArticulosDetalle { get; set; }
        public string IdArticulo { get; set; }
        public string IdBodega { get; set; }
        public Nullable<double> Minimo { get; set; }
        public Nullable<double> Maximo { get; set; }
        public Nullable<double> Pedido { get; set; }
        public Nullable<System.DateTime> UltimaFechaVenta { get; set; }
        public Nullable<System.DateTime> UltimaFechaCompra { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<double> UnidadesIniciales { get; set; }
        public Nullable<double> CostoInicial_Q { get; set; }
        public Nullable<double> UnidadesEntrantes { get; set; }
        public Nullable<double> CostoEntradas_Q { get; set; }
        public Nullable<double> UnidadesSalientes { get; set; }
        public Nullable<double> CostoSalidas_Q { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<double> ExistIniUnidPeriodo { get; set; }
        public Nullable<double> ExistIniValPeriodo { get; set; }
        public Nullable<double> ExistIniUnidReporte { get; set; }
        public Nullable<double> ExistIniValReporte { get; set; }
        public Nullable<System.DateTime> docfechaultcomp1 { get; set; }
        public Nullable<System.DateTime> docfechaultcomp2 { get; set; }
        public Nullable<System.DateTime> docfechaultcomp3 { get; set; }
        public string docultcomp1 { get; set; }
        public string docultcomp2 { get; set; }
        public string docultcomp3 { get; set; }
        public Nullable<System.DateTime> fechaconteofisico { get; set; }
        public Nullable<double> unidadesfisicas { get; set; }
        public Nullable<decimal> valorultcomp1 { get; set; }
        public Nullable<decimal> valorultcomp2 { get; set; }
        public Nullable<decimal> valorultcomp3 { get; set; }
        public Nullable<decimal> CostoPromedioActual_Q_bod { get; set; }
        public Nullable<decimal> CostoPromedioAnterior_Q_bod { get; set; }
        public Nullable<decimal> costo_anterior { get; set; }
        public Nullable<decimal> costo_actual { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoBodegas { get; set; }
        public int IdInternoArticulos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacionesinvdetalle> cotizacionesinvdetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetalleinv> movimientosdetalleinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidosclientesinvdetalle> pedidosclientesinvdetalle { get; set; }
        public virtual articulosinv articulosinv { get; set; }
        public virtual bodegasinv bodegasinv { get; set; }
    }
}
