//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int IdInternoBitacora { get; set; }
        public string Usuario { get; set; }
        public string Codigo_Empresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public string TipoMov { get; set; }
        public string SerieMov { get; set; }
        public string NumdocMov { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string IdVendedor { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public Nullable<System.DateTime> fechahora { get; set; }
        public string tipoaccion { get; set; }
        public string estatus { get; set; }
        public int IdInternoClientes { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
