//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoraresoluciones
    {
        public int IdInternoBitacoraResoluciones { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechahora { get; set; }
        public string idserie { get; set; }
        public string res_del { get; set; }
        public string res_al { get; set; }
        public string resolucionnumero { get; set; }
        public string estatus { get; set; }
        public Nullable<System.DateTime> fechaautorizacion { get; set; }
        public string descripciondoc { get; set; }
        public Nullable<System.DateTime> fechavencimiento { get; set; }
        public string codigo_empresa { get; set; }
    }
}
