//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegasinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bodegasinv()
        {
            this.articulosdetalleinv = new HashSet<articulosdetalleinv>();
            this.movimientoshistoricosinv = new HashSet<movimientoshistoricosinv>();
            this.pedidosclientesinv = new HashSet<pedidosclientesinv>();
            this.movimientosdetallecomboshistoricosinv = new HashSet<movimientosdetallecomboshistoricosinv>();
            this.clientes = new HashSet<clientes>();
            this.pedidostransitoinv = new HashSet<pedidostransitoinv>();
            this.ofertas = new HashSet<ofertas>();
            this.importacionescargosinv = new HashSet<importacionescargosinv>();
            this.cotizacionesinv = new HashSet<cotizacionesinv>();
        }
    
        public int IdInternoBodegas { get; set; }
        public string IdBodega { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Encargado { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string cta_bodega_inventario { get; set; }
        public string idcentrocosto { get; set; }
        public string tipobodega { get; set; }
        public string BodegaCentral { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
        public string Es_sucursal { get; set; }
        public string Usa_multiseries { get; set; }
        public string Serie_fac_env { get; set; }
        public string Serie_mov_inv { get; set; }
        public Nullable<int> fel_emisor_codigo_establecimiento { get; set; }
        public string fel_emisor_direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulosdetalleinv> articulosdetalleinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientoshistoricosinv> movimientoshistoricosinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidosclientesinv> pedidosclientesinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetallecomboshistoricosinv> movimientosdetallecomboshistoricosinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientes> clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidostransitoinv> pedidostransitoinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ofertas> ofertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importacionescargosinv> importacionescargosinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacionesinv> cotizacionesinv { get; set; }
    }
}
