//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacionesinvdetalle
    {
        public int idInternoCotizacionesDetalle { get; set; }
        public string Codigo_Empresa { get; set; }
        public Nullable<int> unidades { get; set; }
        public Nullable<decimal> preciounitario { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public string numdoc { get; set; }
        public string nombrearticulo { get; set; }
        public Nullable<int> unidades_e { get; set; }
        public Nullable<int> unidades_p { get; set; }
        public int idInternoCotizaciones { get; set; }
        public int IdInternoArticulosDetalle { get; set; }
    
        public virtual articulosdetalleinv articulosdetalleinv { get; set; }
        public virtual cotizacionesinv cotizacionesinv { get; set; }
    }
}
