//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacionesinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacionesinv()
        {
            this.cotizacionesinvdetalle = new HashSet<cotizacionesinvdetalle>();
        }
    
        public int idInternoCotizaciones { get; set; }
        public string cotref { get; set; }
        public string direccliente { get; set; }
        public string duracionoferta { get; set; }
        public string entregada { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechaimpresion { get; set; }
        public string impresa { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> montototal { get; set; }
        public string nitcliente { get; set; }
        public string nombrecliente { get; set; }
        public string numdoc { get; set; }
        public string observaciones { get; set; }
        public string telscliente { get; set; }
        public string tiempoentrega { get; set; }
        public string usuarioimpresion { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_empresa { get; set; }
        public int IdInternoClientes { get; set; }
        public int IdInternoBodegas { get; set; }
        public int IdInternoVendedores { get; set; }
    
        public virtual bodegasinv bodegasinv { get; set; }
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacionesinvdetalle> cotizacionesinvdetalle { get; set; }
        public virtual vendedores vendedores { get; set; }
    }
}
