//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_pcsolutions_webEntities : DbContext
    {
        public db_pcsolutions_webEntities()
            : base("name=db_pcsolutions_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulosdetallegenericos> articulosdetallegenericos { get; set; }
        public virtual DbSet<articulosdetalleinv> articulosdetalleinv { get; set; }
        public virtual DbSet<articulosinv> articulosinv { get; set; }
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<bitacoraresoluciones> bitacoraresoluciones { get; set; }
        public virtual DbSet<bodegasinv> bodegasinv { get; set; }
        public virtual DbSet<clases> clases { get; set; }
        public virtual DbSet<clasesproveedores> clasesproveedores { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<cobradores> cobradores { get; set; }
        public virtual DbSet<combosdetalleinv> combosdetalleinv { get; set; }
        public virtual DbSet<cotizacionesinv> cotizacionesinv { get; set; }
        public virtual DbSet<cotizacionesinvdetalle> cotizacionesinvdetalle { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<espera> espera { get; set; }
        public virtual DbSet<esperadetalle> esperadetalle { get; set; }
        public virtual DbSet<estadocivil> estadocivil { get; set; }
        public virtual DbSet<familiasinv> familiasinv { get; set; }
        public virtual DbSet<formulasdetalle> formulasdetalle { get; set; }
        public virtual DbSet<genericos> genericos { get; set; }
        public virtual DbSet<importacionescargosinv> importacionescargosinv { get; set; }
        public virtual DbSet<impresoras> impresoras { get; set; }
        public virtual DbSet<localidades> localidades { get; set; }
        public virtual DbSet<marcasinv> marcasinv { get; set; }
        public virtual DbSet<medidasinv> medidasinv { get; set; }
        public virtual DbSet<movimientoscaja> movimientoscaja { get; set; }
        public virtual DbSet<movimientosdetallecaja> movimientosdetallecaja { get; set; }
        public virtual DbSet<movimientosdetallecomboshistoricosinv> movimientosdetallecomboshistoricosinv { get; set; }
        public virtual DbSet<movimientosdetallecombosinv> movimientosdetallecombosinv { get; set; }
        public virtual DbSet<movimientosdetallehistoricosinv> movimientosdetallehistoricosinv { get; set; }
        public virtual DbSet<movimientosdetalleinv> movimientosdetalleinv { get; set; }
        public virtual DbSet<movimientoshistoricosinv> movimientoshistoricosinv { get; set; }
        public virtual DbSet<movimientosinv> movimientosinv { get; set; }
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<ofertas> ofertas { get; set; }
        public virtual DbSet<ofertasdetalle> ofertasdetalle { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<pedidosclientesinv> pedidosclientesinv { get; set; }
        public virtual DbSet<pedidosclientesinvdetalle> pedidosclientesinvdetalle { get; set; }
        public virtual DbSet<pedidostransitodetallehistoricoinv> pedidostransitodetallehistoricoinv { get; set; }
        public virtual DbSet<pedidostransitodetalleinv> pedidostransitodetalleinv { get; set; }
        public virtual DbSet<pedidostransitohistoricoinv> pedidostransitohistoricoinv { get; set; }
        public virtual DbSet<pedidostransitoinv> pedidostransitoinv { get; set; }
        public virtual DbSet<periodos> periodos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<rutas> rutas { get; set; }
        public virtual DbSet<sectores> sectores { get; set; }
        public virtual DbSet<security_companies> security_companies { get; set; }
        public virtual DbSet<security_company_users> security_company_users { get; set; }
        public virtual DbSet<security_groups> security_groups { get; set; }
        public virtual DbSet<security_users> security_users { get; set; }
        public virtual DbSet<tiposmovimientosinv> tiposmovimientosinv { get; set; }
        public virtual DbSet<tiposmovimientosseriesinv> tiposmovimientosseriesinv { get; set; }
        public virtual DbSet<traslados> traslados { get; set; }
        public virtual DbSet<vendedores> vendedores { get; set; }
        public virtual DbSet<zonas> zonas { get; set; }
        public virtual DbSet<tiposcargosimportacionesinv> tiposcargosimportacionesinv { get; set; }
    }
}
