//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class espera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public espera()
        {
            this.esperadetalle = new HashSet<esperadetalle>();
        }
    
        public int IdInternoEspera { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string nit { get; set; }
        public string transporte { get; set; }
        public string direcciontransporte { get; set; }
        public string registro { get; set; }
        public string giro { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_empresa { get; set; }
        public int IdInternoVendedores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<esperadetalle> esperadetalle { get; set; }
        public virtual vendedores vendedores { get; set; }
    }
}
