//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class esperadetalle
    {
        public int idinterno { get; set; }
        public string codigo_empresa { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> unidades { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> porcentajedescuento { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string oferta { get; set; }
        public int IdInternoEspera { get; set; }
        public int IdInternoArticulos { get; set; }
    
        public virtual articulosinv articulosinv { get; set; }
        public virtual espera espera { get; set; }
    }
}
