//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulasdetalle
    {
        public int IdInternoFormuladetalle { get; set; }
        public string IdArticuloComp { get; set; }
        public string Codigo_Empresa { get; set; }
        public string IdInsumo { get; set; }
        public Nullable<double> unidades { get; set; }
    }
}
