//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class importacionescargosinv
    {
        public int IdInternoImportacionesCargo { get; set; }
        public string Numdoc { get; set; }
        public string Observaciones { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string TipoFac { get; set; }
        public string SerieFac { get; set; }
        public string NumdocFac { get; set; }
        public string Codigo_Empresa { get; set; }
        public string incluyeiva { get; set; }
        public int IdInternoTIposMovimientosSeries { get; set; }
        public int IdInternoBodegas { get; set; }
        public int IdInternoProveedores { get; set; }
        public int IdInternoTipCargImportaciones { get; set; }
    
        public virtual bodegasinv bodegasinv { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual tiposcargosimportacionesinv tiposcargosimportacionesinv { get; set; }
        public virtual tiposmovimientosseriesinv tiposmovimientosseriesinv { get; set; }
    }
}
