//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class impresoras
    {
        public int IdInternoImpresoras { get; set; }
        public string nombrecomputadora { get; set; }
        public string codigo_empresa { get; set; }
        public string sistema { get; set; }
        public string prt_factura { get; set; }
        public string prt_reportes { get; set; }
        public string prt_facturabodega { get; set; }
        public string prt_movimientos { get; set; }
        public string prt_pdf { get; set; }
        public string prt_envios { get; set; }
        public string prt_compras { get; set; }
        public string prt_cotizaciones { get; set; }
    }
}
