//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientoscaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimientoscaja()
        {
            this.movimientosdetallecaja = new HashSet<movimientosdetallecaja>();
        }
    
        public int IdInternoMovimientosCaja { get; set; }
        public int IdCaja { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Final { get; set; }
        public Nullable<decimal> Valor_Inicial { get; set; }
        public Nullable<decimal> Total_Operacion { get; set; }
        public Nullable<decimal> Total_Dinero { get; set; }
        public string Cerrado { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetallecaja> movimientosdetallecaja { get; set; }
    }
}
