//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientoshistoricosinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimientoshistoricosinv()
        {
            this.movimientosdetallehistoricosinv = new HashSet<movimientosdetallehistoricosinv>();
        }
    
        public int IdInternoMovimientosHistoricos { get; set; }
        public string Numdoc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public string Impreso { get; set; }
        public string Anulado { get; set; }
        public string ClienteProveedor { get; set; }
        public Nullable<double> TasaCambio { get; set; }
        public string Pedido { get; set; }
        public string PolizaImportacion { get; set; }
        public string Autorizado { get; set; }
        public string Entregado { get; set; }
        public string CreditoContado { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string NoFactura { get; set; }
        public string TipoFactura { get; set; }
        public string SerieFactura { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string nit { get; set; }
        public string Nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<decimal> Monto_Q { get; set; }
        public Nullable<decimal> Impuesto_Q { get; set; }
        public Nullable<decimal> Descuento_Q { get; set; }
        public Nullable<decimal> MontoArancel { get; set; }
        public string Moneda { get; set; }
        public string LocalExporta { get; set; }
        public string FormaPago { get; set; }
        public string NumCheque { get; set; }
        public string CasaEmisora { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string Domicilio { get; set; }
        public string Descripcion2 { get; set; }
        public string CorrelativoPartida { get; set; }
        public Nullable<System.DateTime> mesanio { get; set; }
        public string usuario { get; set; }
        public string PolizaImportacion2 { get; set; }
        public string TrasladaIVA { get; set; }
        public Nullable<System.DateTime> MesDeclaracionIVA { get; set; }
        public string PesoUnidades { get; set; }
        public string registro { get; set; }
        public string giro { get; set; }
        public string exento { get; set; }
        public Nullable<decimal> valorexento { get; set; }
        public string FacturaContribuyente { get; set; }
        public Nullable<decimal> porcentajeRetencion { get; set; }
        public Nullable<decimal> valorRetencion { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoBodegas { get; set; }
        public int IdInternoVendedores { get; set; }
        public int IdInternoTIposMovimientosSeries { get; set; }
    
        public virtual bodegasinv bodegasinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetallehistoricosinv> movimientosdetallehistoricosinv { get; set; }
        public virtual tiposmovimientosseriesinv tiposmovimientosseriesinv { get; set; }
        public virtual vendedores vendedores { get; set; }
    }
}
