//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientosdetallecaja
    {
        public int IdInternoMovimientosDetalleCaja { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Numdoc { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public string BancoTarjeta { get; set; }
        public string NoTarjeta { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public Nullable<decimal> MontoExtranjera { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
        public string EntradaSalida { get; set; }
        public string Cerrado { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoMovimientosCaja { get; set; }
        public int IdInternoTIposMovimientosSeries { get; set; }
    
        public virtual movimientoscaja movimientoscaja { get; set; }
        public virtual tiposmovimientosseriesinv tiposmovimientosseriesinv { get; set; }
    }
}
