//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public int idInternoMunicipios { get; set; }
        public string IdMunicipio { get; set; }
        public string codigo_empresa { get; set; }
        public string Descripcion { get; set; }
        public int IdInternoDepartamentos { get; set; }
    
        public virtual departamentos departamentos { get; set; }
    }
}
