//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofertasdetalle
    {
        public string IdOferta { get; set; }
        public Nullable<decimal> Unidades { get; set; }
        public Nullable<decimal> PrecioNormal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoOfertas { get; set; }
        public int IdInternoArticulos { get; set; }
    
        public virtual articulosinv articulosinv { get; set; }
        public virtual ofertas ofertas { get; set; }
    }
}
