//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosclientesinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidosclientesinv()
        {
            this.movimientosinv = new HashSet<movimientosinv>();
            this.pedidosclientesinvdetalle = new HashSet<pedidosclientesinvdetalle>();
            this.traslados = new HashSet<traslados>();
        }
    
        public int IdInternoPedidosClientes { get; set; }
        public string Numdoc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public string Impreso { get; set; }
        public string Anulado { get; set; }
        public string ClienteProveedor { get; set; }
        public Nullable<double> TasaCambio { get; set; }
        public string Autorizado { get; set; }
        public string Entregado { get; set; }
        public string CreditoContado { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string NombreCliente { get; set; }
        public string CotizacionPedido { get; set; }
        public string FormaPago { get; set; }
        public string NumCheque { get; set; }
        public string CasaEmisora { get; set; }
        public string Moneda { get; set; }
        public string LocalExportacion { get; set; }
        public string Descripcion2 { get; set; }
        public string Domicilio { get; set; }
        public string NoCotizacion { get; set; }
        public string TiempoEntrega { get; set; }
        public string ValidezOferta { get; set; }
        public string TipoFormaPago { get; set; }
        public string InternoCliente { get; set; }
        public string NumeroTraslado { get; set; }
        public string SerieTraslado { get; set; }
        public string Ingresado { get; set; }
        public string Aceptacheques { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoBodegas { get; set; }
        public int IdInternoVendedores { get; set; }
        public int IdInternoTIposMovimientosSeries { get; set; }
    
        public virtual bodegasinv bodegasinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosinv> movimientosinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidosclientesinvdetalle> pedidosclientesinvdetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traslados> traslados { get; set; }
        public virtual tiposmovimientosseriesinv tiposmovimientosseriesinv { get; set; }
        public virtual vendedores vendedores { get; set; }
    }
}
