//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidostransitohistoricoinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidostransitohistoricoinv()
        {
            this.pedidostransitodetallehistoricoinv = new HashSet<pedidostransitodetallehistoricoinv>();
        }
    
        public int IdInternoPedidosTransitosHistoricos { get; set; }
        public string Numdoc { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaEmbarque { get; set; }
        public Nullable<System.DateTime> FechaRecibido { get; set; }
        public string IdProveedor { get; set; }
        public string Transporte { get; set; }
        public Nullable<decimal> MontoFOB { get; set; }
        public Nullable<decimal> MontoCIF { get; set; }
        public Nullable<decimal> MontoLocal { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string Cerrado { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_Empresa { get; set; }
        public int IdInternoProveedores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidostransitodetallehistoricoinv> pedidostransitodetallehistoricoinv { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
