//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosclientesinvdetalle
    {
        public int IdInternoPedidosClientesDetalle { get; set; }
        public string Numdoc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Precio_unitario { get; set; }
        public Nullable<double> Costo_Unitario { get; set; }
        public Nullable<decimal> PorcentajeDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<double> unidades_e { get; set; }
        public string Codigo_Empresa { get; set; }
        public Nullable<double> Precio_UnitarioE { get; set; }
        public string CotizacionPedido { get; set; }
        public string Autorizacion { get; set; }
        public string NombreArticulo { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public int IdInternoPedidosClientes { get; set; }
        public int IdInternoArticulos { get; set; }
    
        public virtual articulosinv articulosinv { get; set; }
        public virtual pedidosclientesinv pedidosclientesinv { get; set; }
    }
}
