//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodos
    {
        public int IdInternoPeriodos { get; set; }
        public string Sistemav { get; set; }
        public System.DateTime fecha_inicial_periodo { get; set; }
        public Nullable<System.DateTime> fecha_final_periodo { get; set; }
        public Nullable<System.DateTime> fecha_inicial_mes { get; set; }
        public Nullable<System.DateTime> fecha_final_mes { get; set; }
        public string codigo_empresa { get; set; }
    }
}
