//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedores()
        {
            this.articulosinv = new HashSet<articulosinv>();
            this.importacionescargosinv = new HashSet<importacionescargosinv>();
            this.movimientosdetallecombosinv = new HashSet<movimientosdetallecombosinv>();
            this.movimientosdetallehistoricosinv = new HashSet<movimientosdetallehistoricosinv>();
            this.pedidostransitohistoricoinv = new HashSet<pedidostransitohistoricoinv>();
            this.pedidostransitoinv = new HashSet<pedidostransitoinv>();
        }
    
        public int IdInternoProveedores { get; set; }
        public string IdProveedor { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string ApartadoPostal { get; set; }
        public string Cedula { get; set; }
        public string Nit { get; set; }
        public Nullable<System.DateTime> FechadeAlta { get; set; }
        public Nullable<decimal> DiasCredito { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public string Observaciones { get; set; }
        public string E_Mail { get; set; }
        public string DiaPago { get; set; }
        public string PersonaContacto_1 { get; set; }
        public string PersonaContacto_2 { get; set; }
        public string AltaBaja { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<decimal> DiasProntoPago { get; set; }
        public Nullable<decimal> DescProntoPago { get; set; }
        public Nullable<decimal> MontoPorAplicar { get; set; }
        public Nullable<decimal> MontoProvicional { get; set; }
        public Nullable<decimal> SaldoInicioPeriodo { get; set; }
        public Nullable<decimal> MontoPorAplicarPeriodo { get; set; }
        public Nullable<decimal> MontoProvicionalPeriodo { get; set; }
        public string Idcuenta { get; set; }
        public string registro { get; set; }
        public string giro { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string Codigo_empresa { get; set; }
        public int IdInternoClasesProveedores { get; set; }
        public int IdInternoPaises { get; set; }
        public int IdInternoZonas { get; set; }
        public int IdInternoLocalidades { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulosinv> articulosinv { get; set; }
        public virtual clasesproveedores clasesproveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importacionescargosinv> importacionescargosinv { get; set; }
        public virtual localidades localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetallecombosinv> movimientosdetallecombosinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientosdetallehistoricosinv> movimientosdetallehistoricosinv { get; set; }
        public virtual paises paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidostransitohistoricoinv> pedidostransitohistoricoinv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidostransitoinv> pedidostransitoinv { get; set; }
        public virtual zonas zonas { get; set; }
    }
}
