//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_company_users
    {
        public int IdInternoSecurityCompanyUser { get; set; }
        public string codigo_empresa { get; set; }
        public string user_name { get; set; }
        public string application { get; set; }
        public int IdInternoSecurityUser { get; set; }
        public int idInternoSecurityCompany { get; set; }
    
        public virtual security_companies security_companies { get; set; }
        public virtual security_users security_users { get; set; }
    }
}
