//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public security_companies()
        {
            this.security_company_users = new HashSet<security_company_users>();
        }
    
        public int idInternoSecurityCompany { get; set; }
        public string codigo_empresa { get; set; }
        public string nombre { get; set; }
        public string razon_social { get; set; }
        public string direccion { get; set; }
        public string identificacion_tributaria { get; set; }
        public System.DateTime fecha_inicial_periodo { get; set; }
        public System.DateTime fecha_final_periodo { get; set; }
        public System.DateTime fecha_inicial_mes { get; set; }
        public System.DateTime fecha_final_mes { get; set; }
        public string nombre_moneda { get; set; }
        public string nombre_impuesto { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string telefono3 { get; set; }
        public string fax1 { get; set; }
        public string fax2 { get; set; }
        public string persona_encargada { get; set; }
        public string simbolo_moneda { get; set; }
        public Nullable<decimal> porcentaje_impuesto { get; set; }
        public string correo_electronico { get; set; }
        public string apartado_postal { get; set; }
        public string numero_patente { get; set; }
        public System.DateTime feciniper { get; set; }
        public string ubicacion_backup { get; set; }
        public System.DateTime f_ultimo_backup_aut { get; set; }
        public Nullable<sbyte> frecuencia_backup { get; set; }
        public string hacerbackup_auto { get; set; }
        public string ServiciodeMensajes { get; set; }
        public string Interfaz_Conta { get; set; }
        public string Interfaz_cxp { get; set; }
        public string poliza_ingresos { get; set; }
        public string poliza_egresos { get; set; }
        public string clave_autorizo { get; set; }
        public string Tienda { get; set; }
        public string cta_caja { get; set; }
        public string Multitienda { get; set; }
        public string CuentaContableCliente { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public string fel_emisor_afiliacion_iva { get; set; }
        public Nullable<int> fel_emisor_codigo_establecimiento { get; set; }
        public string fel_emisor_codigo_postal { get; set; }
        public string fel_emisor_correo_emisor { get; set; }
        public string fel_emisor_pais { get; set; }
        public string fel_emisor_departamento { get; set; }
        public string fel_emisor_municipio { get; set; }
        public string fel_emisor_nit { get; set; }
        public string fel_emisor_razon_social { get; set; }
        public string fel_emisor_nombre_comercial { get; set; }
        public string fel_usuario { get; set; }
        public string fel_llave_general { get; set; }
        public string fel_llave_pfx { get; set; }
        public string fel_almacenar_local { get; set; }
        public string fel_enviar_correo_cliente { get; set; }
        public string fel_emisor_direccion { get; set; }
        public string fel_almacenar_xml { get; set; }
        public string maneja_sucursales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<security_company_users> security_company_users { get; set; }
    }
}
