//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minible5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public security_users()
        {
            this.security_company_users = new HashSet<security_company_users>();
        }
    
        public int IdInternoSecurityUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> group_id { get; set; }
        public string group { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string status { get; set; }
        public int IdInternoSecurityGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<security_company_users> security_company_users { get; set; }
        public virtual security_groups security_groups { get; set; }
    }
}
